-- NEUTERED 2026-09-12. Intentionally a no-op.
--
-- This migration called run_maintenance_catchup() and then
-- prune_maintenance_payloads() in one DO block to verify both before their
-- first scheduled run. It could never have worked, and it failed on apply:
--
--   * each function is budgeted to return inside ~100 seconds, so the two
--     together take ~200 seconds in ONE statement -- above the ~120s ceiling
--     that cancels long statements on this project (20260906070000);
--   * the backlog counts that followed scan a 7 GB table unindexed on
--     intelligence_factors, which adds more time to the same statement;
--   * the per-call `EXCEPTION WHEN OTHERS` handlers were meant to report a
--     failure instead of aborting, but OTHERS deliberately does not match
--     QUERY_CANCELED -- so a cancellation escaped them and aborted the whole
--     migration, which blocks every later migration in the queue.
--
-- The failed attempt rolled back completely: nothing was deleted or nulled.
--
-- The scheduled jobs are unaffected. cron runs each function on its own
-- (maintenance-catchup-15min at :02/:17/:32/:47, maintenance-payload-prune-15min
-- at :09/:24/:39/:54), each call under the ceiling. Their first runs at 04:02
-- and 04:09 UTC are the verification: look for `maintenance_catchup` and
-- `payload_prune` rows in public.database_maintenance_jobs.
--
-- Kept as a file rather than deleted so the migration history matches what was
-- attempted.

SELECT 1;
